export const GET_PATIENTS_REQUEST = 'GET_PATIENTS_REQUEST'
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS'

export const LOGIN_USER = 'LONG_USER'
export const USER_LOGGEDIN = 'USER_LOGGEDIN'

export const LOGOUT_USER = 'LOGOUT_USER'
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT'

export const SET_ALERT = 'SET_ALERT'
export const RESET_ALERT = 'RESET_ALERT'
